# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.28.1/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.28.1/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/kachunpang/fake-numpy

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/kachunpang/fake-numpy

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.28.1/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.28.1/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/kachunpang/fake-numpy/CMakeFiles /Users/kachunpang/fake-numpy//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/kachunpang/fake-numpy/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named myapi

# Build rule for target.
myapi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 myapi
.PHONY : myapi

# fast build rule for target.
myapi/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myapi.dir/build.make CMakeFiles/myapi.dir/build
.PHONY : myapi/fast

api.o: api.cpp.o
.PHONY : api.o

# target to build an object file
api.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myapi.dir/build.make CMakeFiles/myapi.dir/api.cpp.o
.PHONY : api.cpp.o

api.i: api.cpp.i
.PHONY : api.i

# target to preprocess a source file
api.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myapi.dir/build.make CMakeFiles/myapi.dir/api.cpp.i
.PHONY : api.cpp.i

api.s: api.cpp.s
.PHONY : api.s

# target to generate assembly for a file
api.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myapi.dir/build.make CMakeFiles/myapi.dir/api.cpp.s
.PHONY : api.cpp.s

array.o: array.cpp.o
.PHONY : array.o

# target to build an object file
array.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myapi.dir/build.make CMakeFiles/myapi.dir/array.cpp.o
.PHONY : array.cpp.o

array.i: array.cpp.i
.PHONY : array.i

# target to preprocess a source file
array.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myapi.dir/build.make CMakeFiles/myapi.dir/array.cpp.i
.PHONY : array.cpp.i

array.s: array.cpp.s
.PHONY : array.s

# target to generate assembly for a file
array.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myapi.dir/build.make CMakeFiles/myapi.dir/array.cpp.s
.PHONY : array.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... myapi"
	@echo "... api.o"
	@echo "... api.i"
	@echo "... api.s"
	@echo "... array.o"
	@echo "... array.i"
	@echo "... array.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

